# Generated by Django 4.2 on 2023-07-23 12:30

import uuid

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Goal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                (
                    "created_on",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "modified_on",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                ("deleted", models.BooleanField(db_index=True, default=False)),
                ("label", models.CharField(max_length=255)),
                ("description", models.TextField(null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        editable=False,
                        help_text="The user who owns this goal.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                (
                    "created_on",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "modified_on",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                ("deleted", models.BooleanField(db_index=True, default=False)),
                ("label", models.CharField(max_length=255)),
                ("description", models.TextField(null=True)),
                (
                    "discontinued_on",
                    models.DateTimeField(
                        db_index=True,
                        editable=False,
                        help_text="If not null, this habit is discontinued.",
                        null=True,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        editable=False,
                        help_text="The user who owns this habit.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="habits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HabitLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                (
                    "created_on",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "modified_on",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                ("deleted", models.BooleanField(db_index=True, default=False)),
                ("day", models.DateField()),
                ("remarks", models.TextField()),
                (
                    "habit",
                    models.ForeignKey(
                        editable=False,
                        help_text="The habit this log is for.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="ilgi.habit",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MentalHealth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                (
                    "created_on",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "modified_on",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                ("deleted", models.BooleanField(db_index=True, default=False)),
                ("label", models.CharField(max_length=255)),
                (
                    "score_label_extremely_low",
                    models.CharField(
                        help_text="Score of -3", max_length=255, null=True
                    ),
                ),
                (
                    "score_label_very_low",
                    models.CharField(
                        help_text="Score of -2", max_length=255, null=True
                    ),
                ),
                (
                    "score_label_low",
                    models.CharField(
                        help_text="Score of -1", max_length=255, null=True
                    ),
                ),
                (
                    "score_label_neutral",
                    models.CharField(help_text="Score of 0", max_length=255, null=True),
                ),
                (
                    "score_label_high",
                    models.CharField(help_text="Score of 1", max_length=255, null=True),
                ),
                (
                    "score_label_very_high",
                    models.CharField(help_text="Score of 2", max_length=255, null=True),
                ),
                (
                    "score_label_extremely_high",
                    models.CharField(help_text="Score of 3", max_length=255, null=True),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mental_health_metrics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Milestone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                (
                    "created_on",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "modified_on",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                ("deleted", models.BooleanField(db_index=True, default=False)),
                ("label", models.CharField(max_length=255)),
                ("description", models.TextField(null=True)),
                (
                    "deadline",
                    models.DateTimeField(
                        help_text="If not null, this milestone has a deadline.",
                        null=True,
                    ),
                ),
                (
                    "completion_date",
                    models.DateTimeField(
                        db_index=True,
                        editable=False,
                        help_text="If not null, this milestone is completed.",
                        null=True,
                    ),
                ),
                (
                    "goal",
                    models.ForeignKey(
                        editable=False,
                        help_text="The goal this milestone is for.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="milestones",
                        to="ilgi.goal",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RoutineActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                (
                    "created_on",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "modified_on",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                ("deleted", models.BooleanField(db_index=True, default=False)),
                ("label", models.CharField(max_length=255)),
                ("description", models.TextField(null=True)),
                (
                    "start_time",
                    models.TimeField(help_text="Time of day to start activity"),
                ),
                ("end_time", models.TimeField(help_text="Time of day to end activity")),
                (
                    "on_monday",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether this activity is done on Mondays",
                    ),
                ),
                (
                    "on_tuesday",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether this activity is done on Tuesdays",
                    ),
                ),
                (
                    "on_wednesday",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether this activity is done on Wednesdays",
                    ),
                ),
                (
                    "on_thursday",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether this activity is done on Thursdays",
                    ),
                ),
                (
                    "on_friday",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether this activity is done on Fridays",
                    ),
                ),
                (
                    "on_saturday",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether this activity is done on Saturdays",
                    ),
                ),
                (
                    "on_sunday",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether this activity is done on Sundays",
                    ),
                ),
                (
                    "discontinued_on",
                    models.DateTimeField(
                        editable=False,
                        help_text="If not null, this activity is discontinued.",
                        null=True,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="The user who owns this routine.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routines",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RoutineActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                (
                    "created_on",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "modified_on",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                ("deleted", models.BooleanField(db_index=True, default=False)),
                (
                    "start_time",
                    models.TimeField(help_text="Time of day the activity started"),
                ),
                (
                    "end_time",
                    models.TimeField(help_text="Time of day the activity ended"),
                ),
                ("remarks", models.TextField()),
                (
                    "routine",
                    models.ForeignKey(
                        help_text="The routine activity this log is for.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="ilgi.routineactivity",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MilestoneRoutineActivityRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                (
                    "created_on",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "modified_on",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                ("deleted", models.BooleanField(db_index=True, default=False)),
                ("count", models.IntegerField()),
                ("description", models.TextField(null=True)),
                (
                    "completed_by_activity",
                    models.ForeignKey(
                        editable=False,
                        help_text="The routine activity log that completed this requirement.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="ilgi.routineactivitylog",
                    ),
                ),
                (
                    "milestone",
                    models.ForeignKey(
                        editable=False,
                        help_text="The milestone this requirement is part of.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routine_requirements",
                        to="ilgi.milestone",
                    ),
                ),
                (
                    "routine",
                    models.ForeignKey(
                        editable=False,
                        help_text="The routine activity this requirement is for.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="milestone_requirements",
                        to="ilgi.routineactivity",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MilestoneHabitRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                (
                    "created_on",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "modified_on",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                ("deleted", models.BooleanField(db_index=True, default=False)),
                ("count", models.IntegerField()),
                ("description", models.TextField(null=True)),
                (
                    "completed_by_activity",
                    models.ForeignKey(
                        editable=False,
                        help_text="The habit log that completed this requirement.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="ilgi.habitlog",
                    ),
                ),
                (
                    "habit",
                    models.ForeignKey(
                        editable=False,
                        help_text="The habit this requirement is for.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="milestone_requirements",
                        to="ilgi.habit",
                    ),
                ),
                (
                    "milestone",
                    models.ForeignKey(
                        editable=False,
                        help_text="The milestone this requirement is part of.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="habit_requirements",
                        to="ilgi.milestone",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MentalHealthLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                (
                    "created_on",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "modified_on",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                ("deleted", models.BooleanField(db_index=True, default=False)),
                (
                    "score",
                    models.SmallIntegerField(
                        help_text="Score of the mental health metric",
                        validators=[
                            django.core.validators.MinValueValidator(-3),
                            django.core.validators.MaxValueValidator(3),
                        ],
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now, help_text="Time of log"
                    ),
                ),
                (
                    "mental_health",
                    models.ForeignKey(
                        editable=False,
                        help_text="The mental health metric this log is for.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="ilgi.mentalhealth",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CoffeeType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                (
                    "created_on",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "modified_on",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                ("deleted", models.BooleanField(db_index=True, default=False)),
                ("label", models.CharField(max_length=255)),
                ("price", models.IntegerField(help_text="Price per litre")),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="The user who owns this coffee type.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coffee_types",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CoffeeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                (
                    "created_on",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "modified_on",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                ("deleted", models.BooleanField(db_index=True, default=False)),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Quantity of coffee consumed in litres",
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(0.001),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Time of day the coffee was consumed",
                    ),
                ),
                (
                    "coffee_type",
                    models.ForeignKey(
                        editable=False,
                        help_text="The coffee type this log is for.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="ilgi.coffeetype",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
